site_name: Assembly Line Machines Docs
site_url: https://assemblylinemachines.haydenb.me/index/
site_author: Haydenman2 & NinjaKittens
site_description: Documentation for Minecraft mod Assembly Line Machines.
repo_url: https://github.com/HaydenBelanger/assemblylinemachines

#edit_uri must be updated every time default branch is changed!
edit_uri: edit/1.18.2-dev/docs/

nav:
  - Home: index.md
  - Web Guide (Out-of-Date):
    - Chapter 1 - Primitive: walkthrough/chap1.md
    - Chapter 2 - Kinetic Energy: walkthrough/chap2.md
    - Chapter 3a - Logistics and Machines: walkthrough/chap3.md
  - Developers:
    - Data Types: miscdev/datatypes.md
    - Recipes:
      - Alloying: recipes/alloying.md
      - Fluid Mixing: recipes/fluidbath.md
      - Experience Mill Book: recipes/experiencemill.md
      - Entropy Reactor Waste: recipes/entropyreactor.md
      - Fluid-In-Ground: recipes/fluidinground.md
      - Grinding: recipes/grinding.md
      - Milling: recipes/milling.md
      - Shaping: recipes/shaping.md
      - Purifying: recipes/purifying.md
      - Refining: recipes/refining.md
      - World Corruption: recipes/worldcorruption.md
      - Generator Fluid: recipes/generatorfluid.md
      - Upgrading: recipes/upgrading.md
    - Tags: miscdev/tags.md
    - Reservoir Capability: miscdev/fluidreservoir.md


theme:
  name: material
  palette:
    - scheme: default
      primary: cyan
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark Mode
    - scheme: slate
      primary: teal
      accent: light_blue
      toggle:
        icon: material/toggle-switch
        name: Light Mode

docs_dir: docs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
