license="LGPL-3.0"
modLoader="javafml" #mandatory
loaderVersion="[42,)"
issueTrackerURL="https://github.com/HaydenBelanger/assemblylinemachines/issues"
[[mods]]
	modId="assemblylinemachines"
	version="${file.jarVersion}"
	displayName="Assembly Line Machines"
	updateJSONURL="https://haydenb.me/api/versionhistory.json"
	logoFile="banner-compressed.png" #optional
	authors="Haydenman2 (Hayden) & NinjaKittens (Dax Flame)"
	description='''This is Assembly Line Machines, a complete re-imagining of Minecraft's technological side. This mod features new features and an entirely new progression system, built from the ground up to give much more depth to Minecraft.'''
[[dependencies.assemblylinemachines]]
    modId="forge"
    mandatory=true
    versionRange="[42.0.9,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.assemblylinemachines]]
    modId="jei"
    mandatory=false
    versionRange="[11.2.0,)" #mandatory
    ordering="NONE"
    side="BOTH"